version: '3'
services:
  alpha:
    container_name: alpha
    image: alpha
    ports:
      - 8080:80
  beta:
    container_name: beta
    image: beta
    ports:
      - 8081:80
  #nginx:
  #  container_name: nginx
  #  image: nginx
  #  depends_on:
  #  - beta
  #  - alpha
  #  ports:git 
  #    - 9000:80